% +morpho/Config.m
classdef Config
    properties
        projectDir      string
        remoteBase      string = ""
        remoteLogDir    string = ""

        register    struct
        masking     struct
        subsetter   struct
        qa          struct
        outliner    struct
        finaliser   struct
    end

    methods
        function obj = Config(opts)
            arguments
                opts.projectDir string = string(pwd)
            end
            obj.projectDir = opts.projectDir;
            obj.register  = obj.defaultRegister();
            obj.masking   = obj.defaultMasking();
            obj.subsetter = obj.defaultSubsetter();
            obj.qa        = obj.defaultQA();
            obj.outliner  = obj.defaultOutliner();
            obj.finaliser = obj.defaultFinaliser();
        end

        function p = dir(obj, name)
            arguments
                obj
                name string
            end
            map = dictionary( ...
                "avi_raw",          "avi_raw", ...
                "avi_reg",          "avi_reg", ...
                "reg_transforms",   fullfile("avi_reg","reg_trasforms"), ...
                "reference_run",    "reference_run", ...
                "morph",            "morph", ...
                "morph_avi",        fullfile("morph","avi"), ...
                "morph_mat",        fullfile("morph","mat"), ...
                "mat_sub",          fullfile("morph","mat_sub"), ...
                "log_sub",          fullfile("morph","mat_sub","log_sub"), ...
                "mat_qa",           fullfile("morph","mat_QA"), ...
                "qa_masks",         fullfile("morph","mat_QA_masks"), ...
                "masks",            fullfile("morph","masks"), ...
                "vt_trace",         fullfile("morph","vt_trace"), ...
                "vt_trace_mat",     fullfile("morph","vt_trace_mat"), ...
                "vt_trace_avi",     fullfile("morph","vt_trace_avi"), ...
                "vt_skeleton",      fullfile("morph","vt_skeleton"), ...
                "vt_endpoints",     fullfile("morph","vt_endpoints"), ...
                "vt_trace_final",         fullfile("morph","vt_trace","finaliser"), ...
                "vt_trace_mat_final",     fullfile("morph","vt_trace_mat","finaliser"), ...
                "vt_trace_avi_final",     fullfile("morph","vt_trace_avi","finaliser"), ...
                "vt_endpoints_final",     fullfile("morph","vt_endpoints","finaliser"), ...
                "logs_local",       "logs" ...
            );
            p = fullfile(obj.projectDir, map(name));
        end

        function ensure(obj, name)
            d = obj.dir(name);
            if ~isfolder(d), mkdir(d); end
        end

        function names = all_dir_names(~)
            % Return all known directory keys (useful for batch ensure)
            names = ["avi_raw","avi_reg","reg_transforms","reference_run", ...
                     "morph","morph_avi","morph_mat","mat_sub","log_sub", ...
                     "mat_qa","qa_masks","masks","vt_trace","vt_trace_mat", ...
                     "vt_trace_avi","vt_skeleton","vt_endpoints", ...
                     "vt_trace_final","vt_trace_mat_final", ...
                     "vt_trace_avi_final","vt_endpoints_final","logs_local"];
        end
    end

    methods (Static)
        function s = defaultRegister()
            s = struct( ...
                'reference_frame', 100 ...
            );
        end

        function s = defaultMasking()
            s = struct( ...
                'skip_manual_mask_edit_if_shared_mask_loaded', false, ...   %true - skip masking window
                'use_saved_manual_threshold_if_available', false, ...       %true - skip threshold window
                'use_saved_mask_if_available', true, ...
                'warn_if_mask_missing', true, ...
                'save_manual_threshold_for_group', true, ...
                'warn_if_manual_threshold_missing', true, ...
                'mask_opacity', 0.45, ...
                'automatic_var_threshold', true, ...
                'var_threshold', 0.01, ...
                'mask_thickening', 10, ...
                'final_erode', 3, ...
                'automatic_tissue_threshold', false, ...
                'manual_tissue_threshold_chooser', true, ...
                'manual_tissue_threshold', 62, ...
                'lip_clip', true, ...
                'context_frame_chooser', "manual", ...
                'context_frame_default', 100, ...
                'draw_mode', 'D', ...
                'brush_size', 3 ...
            );
        end

        function s = defaultSubsetter()
            s = struct( ...
                'use_logfile', false ...
            );
        end

        function s = defaultQA()
            s = struct( ...
                'use_saved_QA_mask_if_available', true, ...
                'skip_manual_QA_if_shared_mask_loaded', true, ...
                'save_shared_QA_mask_for_group', true, ...
                'warn_if_QA_mask_missing', true, ...
                'brush_size', 3, ...
                'draw_mode', 'E', ...
                'context_frame_chooser', "manual", ...
                'context_frame_default', 100 ...
            );
        end

        function s = defaultOutliner()
            s = struct( ...
                'draw_connector', "a_star", ...
                'a_star_weight', 999, ...
                'lambda', 0.5, ...
                'wantplot', false, ...
                'polynomial_degree', 2, ...
                'manual_check', false, ...
                'suspicion_threshold', 30, ...
                'vt_skel_thresh', 0.75, ...
                'scaling_factor', 5 ...
            );
        end

        function s = defaultFinaliser()
            s = struct( ...
                'scaling_factor', 1.5, ...
                'brush_size', 5, ...
                'draw_mode', 'E' ...
            );
        end
    end
end
